In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk import tokenize
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [4]:
df=pd.read_csv("D:\disaster_tweets_data(DS).csv")
df1=pd.read_csv("D:\disaster_tweets_data(DS).csv")
df.head()

tweets  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [5]:
#CHECKING NULL VALUES
df.isnull().sum()


tweets    0
target    0
dtype: int64

In [6]:
df=df.iloc[:,:1]
df.head()

tweets
0  Our Deeds are the Reason of this #earthquake M...
1             Forest fire near La Ronge Sask. Canada
2  All residents asked to 'shelter in place' are ...
3  13,000 people receive #wildfires evacuation or...
4  Just got sent this photo from Ruby #Alaska as ...

In [8]:
#PREPROCESSING DATA
sw=stopwords.words('English')
print(sw)
lm=WordNetLemmatizer()
data=[]
for i in df['tweets']:    
    t=i.lower() #converting to lower
    t=re.sub('[^A-Za-z]',' ',t) #removing punctuations
    t=word_tokenize(t) #tokenizing
    t=[i for i in t if i not in sw] #removing stop words
    t=[lm.lemmatize(i) for i in t] #lemmatization
    data.append(t)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [9]:
cleansed_tweet=[]
for i in df['tweets']:
    t=i.lower() #converting to lower
    t=re.sub('[^A-Za-z]',' ',t) #removing punctuations
    t=word_tokenize(t) #tokenizing
    t=[i for i in t if i not in sw] #removing stop words
    t=[lm.lemmatize(i) for i in t] #lemmatization
    t=" ".join(t)
    cleansed_tweet.append(t)

In [10]:
#VECTORIZATION
cv=CountVectorizer()
res_cv=cv.fit_transform(cleansed_tweet).toarray()
print(cv.get_feature_names_out())
print(len(cv.get_feature_names_out()))
print(res_cv)

['aa' 'aaaa' 'aaaaaaallll' ... 'zzuz' 'zzweeezjug' 'zzzz']
20675
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
#SELECTING INDEPENDENT AND DEPENDENT FEATURES AS TWEETS AND TARGET
x = np.array(cleansed_tweet)
y =df1['target']
print(type(x))
print(type(y))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [12]:
#SPLITING INTO TEST AND TRAIN DATA
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
cv.fit(x_train)
x_train_cv=cv.transform(x_train).toarray()
x_test_cv=cv.transform(x_test).toarray()
print(x_train_cv.shape)
print(x_test_cv.shape)

(5709,)
(1904,)
(5709,)
(1904,)
(5709, 16959)
(1904, 16959)


In [13]:
#MODEL BUILDING
#1)Multinomial Naive Bayes Classification
nb_classifier=MultinomialNB()
nb_classifier.fit(x_train_cv,y_train)
print('Train Score',nb_classifier.score(x_train_cv,y_train))
print('Test Score',nb_classifier.score(x_test_cv,y_test))

Train Score 0.928709055876686
Test Score 0.7946428571428571


In [15]:
#2)Logistic Regression
lr_classifier = LogisticRegression()
lr_classifier.fit(x_train_cv,y_train)
print('Train Score',lr_classifier.score(x_train_cv,y_train))
print('Test Score',lr_classifier.score(x_test_cv,y_test))

Train Score 0.9740760203187949
Test Score 0.7993697478991597


In [16]:
#3)KNN Classification
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(x_train_cv,y_train)
print('Train Score',knn_classifier.score(x_train_cv,y_train))
print('Test Score',knn_classifier.score(x_test_cv,y_test))

Train Score 0.7087055526361885
Test Score 0.6712184873949579


In [19]:
#Predicting the data
nb_predictions = nb_classifier.predict(x_test_cv)
lr_predictions = lr_classifier.predict(x_test_cv)
knn_predictions = knn_classifier.predict(x_test_cv)

In [20]:
nb_confusion_matrix = confusion_matrix(y_test, nb_predictions)
nb_classification_report = classification_report(y_test, nb_predictions)
lr_confusion_matrix = confusion_matrix(y_test, lr_predictions)
lr_classification_report = classification_report(y_test, lr_predictions)
nb_confusion_matrix = confusion_matrix(y_test, knn_predictions)
nb_classification_report = classification_report(y_test, knn_predictions)

In [21]:
#confusion matrix and classification report for Multinomial Naive Bayes Classification
print(confusion_matrix(y_test,nb_predictions))
print(classification_report(y_test,nb_predictions))

[[908 183]
 [208 605]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82      1091
           1       0.77      0.74      0.76       813

    accuracy                           0.79      1904
   macro avg       0.79      0.79      0.79      1904
weighted avg       0.79      0.79      0.79      1904



In [22]:
#confusion matrix and classification report for Logistic Regression
print(confusion_matrix(y_test,lr_predictions))
print(classification_report(y_test,lr_predictions))

[[944 147]
 [235 578]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83      1091
           1       0.80      0.71      0.75       813

    accuracy                           0.80      1904
   macro avg       0.80      0.79      0.79      1904
weighted avg       0.80      0.80      0.80      1904



In [23]:
#confusion matrix and classification report for KNN Classification
print(confusion_matrix(y_test,knn_predictions))
print(classification_report(y_test,knn_predictions))

[[1079   12]
 [ 614  199]]
              precision    recall  f1-score   support

           0       0.64      0.99      0.78      1091
           1       0.94      0.24      0.39       813

    accuracy                           0.67      1904
   macro avg       0.79      0.62      0.58      1904
weighted avg       0.77      0.67      0.61      1904



In [25]:
#REPORTING THE BEST ACCURACY MODEL
accuracy_knn=accuracy_score(y_test,knn_predictions)
accuracy_lr=accuracy_score(y_test,lr_predictions)
accuracy_nb=accuracy_score(y_test,nb_predictions)
print(f"Accuracy - k-nearest neighbors: {accuracy_knn:.2f}")
print(f"Accuracy - logistic regression: {accuracy_lr:.2f}")
print(f"Accuracy - multinomial Naive Bayes: {accuracy_nb:.2f}")
best_model=None
best_accuracy=0.0
best_model = None
best_accuracy = 0.0

if accuracy_knn > best_accuracy:
    best_model = "k-nearest neighbors"
    best_accuracy = accuracy_knn
    
if accuracy_lr > best_accuracy:
    best_model = "logistic regression"
    best_accuracy = accuracy_lr
    
if accuracy_nb > best_accuracy:
    best_model = "multinomial Naive Bayes"
    best_accuracy = accuracy_mnb
    
print(f"The best model is: {best_model} with an accuracy of {best_accuracy:.2f}")

Accuracy - k-nearest neighbors: 0.67
Accuracy - logistic regression: 0.80
Accuracy - multinomial Naive Bayes: 0.79
The best model is: logistic regression with an accuracy of 0.80
